[package]
name = "voting_contract"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = { version = "20.3.2" }

[dev-dependencies]
soroban-sdk = { version = "20.3.2", features = ["testutils"] }
