#!/bin/bash

if git diff --cached --name-only | grep -q "^apps/frontend/"; then
  echo "Changes detected in frontend. Running lint."
  npx nx lint frontend --fix
else
  echo "No changes detected in frontend."
fi

if git diff --cached --name-only | grep -q "^apps/backend/"; then
  echo "Changes detected in backend. Running lint."
  npx nx lint backend --fix
else
  echo "No changes detected in backend."
fi

npx nx format:write --all
