#!/bin/bash

if git diff --name-only HEAD~1 HEAD | grep -q "^apps/frontend/"; then
  echo "Changes detected in frontend. Running lint and format."
  npx nx lint frontend --fix
  npx nx format:check apps/frontend
  npx nx format:write apps/frontend
else
  echo "No changes detected in frontend."
fi

if git diff --name-only HEAD~1 HEAD | grep -q "^apps/backend/"; then
  echo "Changes detected in backend. Running lint and format."
  npx nx lint backend --fix
  npx nx format:check apps/backend
  npx nx format:write apps/backend
else
  echo "No changes detected in backend."
fi

npx nx format:write --all

